name: Executar Testes Automatizados

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: carteira_test
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_PASSWORD: root
        ports:
          - "3306:3306"

    steps:
      - uses: actions/checkout@v2
      
      - name: Configurar JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Configurar Maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Executar os testes
        run: mvn clean test --file pom.xml

